apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: animal-album
spec:
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: 9000
    name: minio-api
  - port: 9001
    targetPort: 9001
    name: minio-console
  type: ClusterIP
