apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: sayedimran/fastapi-sample-app:v1.0.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 7000

---

apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
spec:
  type: NodePort
  selector:
    app: fastapi-app
  ports:
  - port: 7000
    targetPort: 7000
    nodePort: 30070
    