apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    istio-injection: enabled

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
      - name: minio-storage
        persistentVolumeClaim:
          claimName: minio-pvc
      initContainers:
      - name: restore-minio
        image: sayedimran/curl-tar:v1.0.0
        command: ["sh", "-c", "curl -Lo /data/animal-images.tar.gz https://github.com/Sayed-Imran/DevOps-and-Cloud/raw/refs/heads/master/Sample-Apps/animal-images-display-app/minio-storage/animal-images.tar.gz && tar -xvf /data/animal-images.tar.gz -C /data && rm /data/animal-images.tar.gz"]
        volumeMounts:
        - name: minio-storage
          mountPath: /data
      containers:
      - name: minio
        image: quay.io/minio/minio
        command: ["minio", "server", "/data", "--console-address", ":9001"]
        volumeMounts:
        - name: minio-storage
          mountPath: /data


---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: 9000
    name: minio-api
  - port: 9001
    targetPort: 9001
    name: minio-console
  type: ClusterIP
