apiVersion: networking.istio.io/v1beta1
kind: WorkloadGroup
metadata:
  name: data-service
  namespace: animal-album
spec:
  metadata:
    labels:
      app: data-service
  template:
    serviceAccount: data-service-sa
