apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-auth-server
spec:
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
      - name: auth-server
        image: sayedimran/istio-ext-auth:v1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: ext-auth-server
spec:
  type: ClusterIP
  selector:
    app: auth-server
  ports:
  - port: 8000
    targetPort: 8000
