apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: animal-album-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - 'app.devopsguru.engineer'
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - 'app.devopsguru.engineer'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: animal-album-tls