apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service
  namespace: animal-album
spec:
  selector:
    matchLabels:
      app: ui-service
  template:
    metadata:
      labels:
        app: ui-service
    spec:
      containers:
      - name: ui-service
        image: sayedimran/animal-ui-service:v1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: animal-album
spec:
  selector:
    app: ui-service
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ui-service
  namespace: animal-album
spec:
  gateways:
  - istio-system/animal-album-gateway
  hosts:
  - "app.devopsguru.engineer"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: ui-service.animal-album.svc.cluster.local
