apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
spec:
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      containers:
      - name: data-service
        image: sayedimran/animal-data-service:v1.0.0
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_URI
        - name: IMAGE_SERVICE
          value: "http://image-service.default.svc:8080"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: data-service
spec:
  selector:
    app: data-service
  ports:
  - port: 80
    targetPort: 8080
