apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-service-sa
  namespace: animal-album

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  namespace: animal-album
spec:
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      serviceAccountName: data-service-sa
      containers:
      - name: data-service
        image: sayedimran/animal-data-service:v1.0.0
        imagePullPolicy: Always
        env:
        - name: MONGO_URI
          value: "mongodb://mongo.animal-album.svc:27017/"
        - name: IMAGE_SERVICE
          value: "http://image-service.default.svc:8080"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: animal-album
spec:
  selector:
    app: data-service
  ports:
  - port: 80
    targetPort: 8080

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: data-service
  namespace: animal-album
spec:
  gateways:
  - istio-system/animal-album-gateway
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /data/
    rewrite:
      uri: /
    route:
    - destination:
        host: data-service.animal-album.svc.cluster.local
        port:
          number: 80

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: animal-album-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - '*'
