apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: animal-album
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      serviceAccountName: mongo-sa
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
      containers:
      - name: mongo
        image: mongo:8.0.0
        volumeMounts:
        - mountPath: /data/db
          name: mongo-persistent-storage
        ports:
        - containerPort: 27017
