apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ VS_NAME }}
  namespace: {{ NAMESPACE }}
spec:
  hosts:
  - "{{ DOMAIN }}"
  gateways:
  - istio-system/tls-gateway
  http:
  - route:
    - destination:
        port:
          number: 8000
        host: fastapi-app.default.svc.cluster.local