apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-service-sa
  namespace: animal-album

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
  namespace: animal-album
spec:
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      serviceAccountName: image-service-sa
      containers:
      - name: image-service
        image: sayedimran/animal-image-service:v1.0.0
        imagePullPolicy: Always
        env:
        - name: MINIO_ENDPOINT
          value: "minio.animal-album.svc:9000"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  name: image-service
  namespace: animal-album
spec:
  selector:
    app: image-service
  ports:
  - port: 80
    targetPort: 8000

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: image-service
  namespace: animal-album
spec:
  gateways:
  - istio-system/animal-album-gateway
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /images
    route:
    - destination:
        host: data-service.animal-album.svc.cluster.local
